/**
 * Badge definitions for the ChefCast: Live gamification system.
 * Each badge has a slug, name, description, icon, XP reward, and unlock criteria.
 */

import { Badge } from "@/types";

export const ALL_BADGES: Omit<Badge, "isUnlocked" | "earnedAt" | "progress">[] = [
  {
    id: "badge-knife-master",
    slug: "knife_master",
    name: "Knife Master",
    description: "Complete 5 steps tagged with knife work technique",
    iconName: "scissors",
    xpReward: 100,
    unlockCriteria: "Complete 5 knife_work steps",
    maxProgress: 5,
  },
  {
    id: "badge-sauce-expert",
    slug: "sauce_expert",
    name: "Sauce Expert",
    description: "Complete 5 steps tagged with sauce technique",
    iconName: "droplet",
    xpReward: 100,
    unlockCriteria: "Complete 5 sauce steps",
    maxProgress: 5,
  },
  {
    id: "badge-speed-demon",
    slug: "speed_demon",
    name: "Speed Demon",
    description: "Complete a cook session in under 80% of estimated time",
    iconName: "zap",
    xpReward: 150,
    unlockCriteria: "Finish a session 20% faster than estimated",
    maxProgress: 1,
  },
  {
    id: "badge-streak-3",
    slug: "streak_3",
    name: "On Fire",
    description: "Cook 3 days in a row",
    iconName: "flame",
    xpReward: 75,
    unlockCriteria: "3-day cooking streak",
    maxProgress: 3,
  },
  {
    id: "badge-streak-7",
    slug: "streak_7",
    name: "Week Warrior",
    description: "Cook 7 days in a row",
    iconName: "calendar",
    xpReward: 200,
    unlockCriteria: "7-day cooking streak",
    maxProgress: 7,
  },
  {
    id: "badge-streak-30",
    slug: "streak_30",
    name: "Monthly Master",
    description: "Cook 30 days in a row",
    iconName: "award",
    xpReward: 1000,
    unlockCriteria: "30-day cooking streak",
    maxProgress: 30,
  },
  {
    id: "badge-mystery-winner",
    slug: "mystery_winner",
    name: "Mystery Winner",
    description: "Have a mystery box submission featured on TV",
    iconName: "star",
    xpReward: 500,
    unlockCriteria: "Get featured on the show",
    maxProgress: 1,
  },
  {
    id: "badge-community-star",
    slug: "community_star",
    name: "Community Star",
    description: "Receive 50 total likes on your dish photos",
    iconName: "heart",
    xpReward: 200,
    unlockCriteria: "50 total likes on dish photos",
    maxProgress: 50,
  },
  {
    id: "badge-poll-voter",
    slug: "poll_voter",
    name: "Poll Voter",
    description: "Vote in 10 live polls",
    iconName: "bar-chart-2",
    xpReward: 100,
    unlockCriteria: "Vote in 10 polls",
    maxProgress: 10,
  },
  {
    id: "badge-first-cook",
    slug: "first_cook",
    name: "First Cook",
    description: "Complete your first cook session",
    iconName: "chef-hat",
    xpReward: 50,
    unlockCriteria: "Complete a cook session",
    maxProgress: 1,
  },
  {
    id: "badge-perfect-plate",
    slug: "perfect_plate",
    name: "Perfect Plate",
    description: "Upload a photo AND complete all steps in a session",
    iconName: "camera",
    xpReward: 200,
    unlockCriteria: "Full session + photo upload",
    maxProgress: 1,
  },
  {
    id: "badge-early-bird",
    slug: "early_bird",
    name: "Early Bird",
    description: "Watch an episode within the first 5 minutes of going live",
    iconName: "sunrise",
    xpReward: 75,
    unlockCriteria: "Tune in within 5 min of live start",
    maxProgress: 1,
  },
];
