/**
 * Badge definitions for the ChefCast: Live gamification system.
 * Each badge has a slug, name, description, icon, XP reward, and unlock criteria.
 * Based on v2.0 specification.
 */

import { Badge } from "@/types";

export const ALL_BADGES: Omit<Badge, "isUnlocked" | "earnedAt" | "progress">[] = [
  {
    id: "badge-first-answer",
    slug: "first_answer",
    name: "First Answer",
    description: "Submit an answer in the very first live quiz",
    iconName: "check-circle",
    xpReward: 25,
    unlockCriteria: "Submit first quiz answer",
    maxProgress: 1,
  },
  {
    id: "badge-perfect-round",
    slug: "perfect_round",
    name: "Perfect Round",
    description: "Answer all questions correctly in a single episode",
    iconName: "award",
    xpReward: 200,
    unlockCriteria: "100% correct answers in one episode",
    maxProgress: 1,
  },
  {
    id: "badge-speed-king",
    slug: "speed_king",
    name: "Speed King",
    description: "Claim the speed bonus on 10 or more questions",
    iconName: "zap",
    xpReward: 75,
    unlockCriteria: "Speed bonus on 10+ questions",
    maxProgress: 10,
  },
  {
    id: "badge-top-3",
    slug: "top_3",
    name: "Top 3",
    description: "Finish in the top 3 on any episode leaderboard",
    iconName: "trophy",
    xpReward: 100,
    unlockCriteria: "Top 3 finish",
    maxProgress: 1,
  },
  {
    id: "badge-comeback-kid",
    slug: "comeback_kid",
    name: "Comeback Kid",
    description: "Finish top 10 after being outside the top 50 at the halfway point",
    iconName: "trending-up",
    xpReward: 100,
    unlockCriteria: "Top 10 comeback from 50+",
    maxProgress: 1,
  },
  {
    id: "badge-mystery-winner",
    slug: "mystery_winner",
    name: "Mystery Winner",
    description: "Have a Mystery Box submission featured on TV",
    iconName: "star",
    xpReward: 200,
    unlockCriteria: "Mystery Box featured on TV",
    maxProgress: 1,
  },
  {
    id: "badge-community-star",
    slug: "community_star",
    name: "Community Star",
    description: "Receive 50 total likes on dish photos",
    iconName: "heart",
    xpReward: 100,
    unlockCriteria: "50 total likes on dish photos",
    maxProgress: 50,
  },
  {
    id: "badge-loyal-viewer",
    slug: "loyal_viewer",
    name: "Loyal Viewer",
    description: "Participate in 10 live episodes",
    iconName: "tv",
    xpReward: 150,
    unlockCriteria: "Participate in 10 episodes",
    maxProgress: 10,
  },
  {
    id: "badge-early-bird",
    slug: "early_bird",
    name: "Early Bird",
    description: "Join a live quiz within 2 minutes of broadcast start",
    iconName: "sunrise",
    xpReward: 30,
    unlockCriteria: "Join within 2 min of start",
    maxProgress: 1,
  },
  {
    id: "badge-perfect-plate",
    slug: "perfect_plate",
    name: "Perfect Plate",
    description: "Upload a dish photo AND answer all questions in an episode",
    iconName: "camera",
    xpReward: 100,
    unlockCriteria: "Photo upload + all questions answered",
    maxProgress: 1,
  },
];
