/**
 * Mock data for development. Simulates what Supabase would return.
 * In production, replace these with real Supabase queries.
 */

import { Episode, Recipe, CommunityPost, QAQuestion, LeaderboardEntry, MysteryBoxSubmission } from "@/types";

export const MOCK_EPISODES: Episode[] = [
  {
    id: "ep-001",
    title: "Italian Risotto Night",
    description: "Join Chef Marco as he guides you through a perfect saffron risotto with wild mushrooms — a dish that demands patience and rewards with perfection.",
    thumbnailUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
    broadcastAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    isLive: true,
    chefName: "Chef Marco Rossi",
    season: 3,
    episodeNumber: 8,
    difficulty: "medium",
    duration: 45,
  },
  {
    id: "ep-002",
    title: "Pan-Seared Duck Breast",
    description: "Master the art of perfectly rendered duck skin with Chef Sophie's foolproof method. Served with a cherry reduction that will blow your mind.",
    thumbnailUrl: "https://images.unsplash.com/photo-1544025162-d76594f9df0f?w=800",
    broadcastAt: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    isLive: false,
    chefName: "Chef Sophie Laurent",
    season: 3,
    episodeNumber: 9,
    difficulty: "hard",
    duration: 55,
  },
  {
    id: "ep-003",
    title: "Classic French Onion Soup",
    description: "Low and slow, then fast and furious. Chef Jean-Pierre reveals the secrets to the most comforting bowl of soup ever created.",
    thumbnailUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
    broadcastAt: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    isLive: false,
    chefName: "Chef Jean-Pierre",
    season: 3,
    episodeNumber: 10,
    difficulty: "easy",
    duration: 40,
  },
  {
    id: "ep-004",
    title: "Japanese Ramen from Scratch",
    description: "From bone broth to perfect noodles, this is the complete ramen experience you've been dreaming about.",
    thumbnailUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    broadcastAt: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    isLive: false,
    chefName: "Chef Yuki Tanaka",
    season: 3,
    episodeNumber: 11,
    difficulty: "hard",
    duration: 90,
  },
];

export const MOCK_RECIPE: Recipe = {
  id: "recipe-001",
  episodeId: "ep-001",
  title: "Saffron Risotto with Wild Mushrooms",
  description: "A classic Northern Italian dish that rewards patience with incredible depth of flavor.",
  difficulty: "medium",
  prepTimeMinutes: 15,
  cookTimeMinutes: 30,
  servings: 4,
  ingredients: [
    { id: "ing-1", name: "Arborio rice", quantity: "400", unit: "g", isOptional: false, stepNumber: 3 },
    { id: "ing-2", name: "Saffron threads", quantity: "1", unit: "pinch", isOptional: false, stepNumber: 4 },
    { id: "ing-3", name: "White wine", quantity: "150", unit: "ml", isOptional: false, stepNumber: 4 },
    { id: "ing-4", name: "Chicken stock", quantity: "1.2", unit: "L", isOptional: false, stepNumber: 5 },
    { id: "ing-5", name: "Wild mushrooms", quantity: "300", unit: "g", isOptional: false, stepNumber: 2 },
    { id: "ing-6", name: "Shallots", quantity: "3", unit: "large", isOptional: false, stepNumber: 1 },
    { id: "ing-7", name: "Garlic cloves", quantity: "2", unit: "cloves", isOptional: false, stepNumber: 1 },
    { id: "ing-8", name: "Parmesan", quantity: "80", unit: "g", isOptional: false, stepNumber: 7 },
    { id: "ing-9", name: "Unsalted butter", quantity: "60", unit: "g", isOptional: false, stepNumber: 7 },
    { id: "ing-10", name: "Olive oil", quantity: "3", unit: "tbsp", isOptional: false, stepNumber: 1 },
    { id: "ing-11", name: "Truffle oil", quantity: "1", unit: "tsp", isOptional: true, stepNumber: 8 },
    { id: "ing-12", name: "Fresh thyme", quantity: "4", unit: "sprigs", isOptional: false, stepNumber: 2 },
  ],
  steps: [
    {
      id: "step-1",
      stepNumber: 1,
      instruction: "Finely dice the shallots and mince the garlic. Keep them separate — they'll go in at different times. Your mise en place here is key to the whole dish.",
      durationSeconds: 240,
      techniqueTag: "knife_work",
      tip: "Use a sharp chef's knife and consistent cuts. Uneven pieces cook at different rates and will throw off your risotto.",
      ingredientIds: ["ing-6", "ing-7", "ing-10"],
    },
    {
      id: "step-2",
      stepNumber: 2,
      instruction: "Clean and roughly chop the wild mushrooms. In a hot pan with a little olive oil, sear the mushrooms until golden-brown and all moisture has evaporated. Add thyme, season, and set aside.",
      durationSeconds: 480,
      techniqueTag: "sauté",
      tip: "Don't crowd the pan! Work in batches if needed. Crowding causes steaming, not searing.",
      ingredientIds: ["ing-5", "ing-12"],
    },
    {
      id: "step-3",
      stepNumber: 3,
      instruction: "In a large, wide pan, heat the remaining olive oil over medium heat. Add shallots and sweat until completely soft and translucent — about 5 minutes. Add garlic and cook for 30 seconds. Toast the Arborio rice, stirring constantly, until the edges turn translucent.",
      durationSeconds: 360,
      techniqueTag: "knife_work",
      tip: "Toasting the rice coats each grain with fat — this is what gives risotto its creamy exterior.",
      ingredientIds: ["ing-1", "ing-6", "ing-7"],
    },
    {
      id: "step-4",
      stepNumber: 4,
      instruction: "Add the white wine and stir vigorously until completely absorbed. Meanwhile, steep the saffron in 2 tbsp of warm stock. Add the saffron stock to the rice.",
      durationSeconds: 180,
      techniqueTag: "sauce",
      tip: "The sizzle when wine hits the pan is the sound of alcohol evaporating. Keep stirring — don't let it stick.",
      ingredientIds: ["ing-2", "ing-3"],
    },
    {
      id: "step-5",
      stepNumber: 5,
      instruction: "Add the warm stock one ladle at a time, stirring constantly and waiting for each addition to be almost fully absorbed before adding the next. Maintain a gentle simmer throughout. This process takes 18-22 minutes.",
      durationSeconds: 1200,
      techniqueTag: "sauce",
      tip: "The constant stirring releases starch from the rice. This is where the creaminess comes from — not from cream!",
      ingredientIds: ["ing-4"],
    },
    {
      id: "step-6",
      stepNumber: 6,
      instruction: "When the rice is al dente — tender but with a slight bite — remove from heat. Fold in the sautéed mushrooms and incorporate them through the risotto.",
      durationSeconds: 60,
      techniqueTag: "knife_work",
      tip: "Al dente means 'to the tooth' — it should have a very slight resistance when you bite into a grain.",
      ingredientIds: ["ing-5"],
    },
    {
      id: "step-7",
      stepNumber: 7,
      instruction: "Off the heat, fold in cold butter and freshly grated Parmesan. Beat vigorously with a wooden spoon to create a creamy, emulsified sauce. This is called 'mantecatura' and it's the soul of risotto.",
      durationSeconds: 120,
      techniqueTag: "sauce",
      tip: "Cold butter is crucial. Warm butter won't emulsify properly and you'll end up with a greasy risotto.",
      ingredientIds: ["ing-8", "ing-9"],
    },
    {
      id: "step-8",
      stepNumber: 8,
      instruction: "Taste and season with salt. Plate immediately — risotto waits for no one. Add a drizzle of truffle oil if using, a few mushrooms on top, and shave some Parmesan over the dish. Serve in warmed bowls.",
      techniqueTag: "plating",
      tip: "Warm your bowls in the oven first. A cold bowl will set the risotto before your guests take their first bite.",
      ingredientIds: ["ing-11"],
    },
  ],
};

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "post-1",
    userId: "user-2",
    username: "foodie_sara",
    episodeTitle: "Italian Risotto Night",
    photoUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=500",
    caption: "My best risotto yet! The saffron color is everything 🔥",
    likes: 142,
    isLiked: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "post-2",
    userId: "user-3",
    username: "chef_at_home",
    episodeTitle: "Italian Risotto Night",
    photoUrl: "https://images.unsplash.com/photo-1544025162-d76594f9df0f?w=500",
    caption: "First time making risotto and I nailed it! Thank you ChefCast",
    likes: 89,
    isLiked: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "post-3",
    userId: "user-4",
    username: "weekend_warrior",
    episodeTitle: "Pan-Seared Duck Breast",
    photoUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500",
    caption: "Duck was perfectly medium-rare. That skin crisp though!",
    likes: 234,
    isLiked: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "post-4",
    userId: "user-5",
    username: "pasta_queen",
    episodeTitle: "Italian Risotto Night",
    photoUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500",
    caption: "Mantecatura is an art form. Mine is getting there!",
    likes: 67,
    isLiked: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
];

export const MOCK_QA: QAQuestion[] = [
  {
    id: "qa-1",
    userId: "user-6",
    username: "kitchen_newbie",
    question: "Can I use regular long-grain rice instead of Arborio?",
    upvotes: 24,
    isAnswered: true,
    answer: "No! Arborio or Carnaroli are essential. They have high starch content which creates the creamy texture. Long-grain rice won't work.",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: "qa-2",
    userId: "user-7",
    username: "curious_cook",
    question: "Why does my risotto always turn gluggy?",
    upvotes: 18,
    isAnswered: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "qa-3",
    userId: "user-8",
    username: "flavor_chaser",
    question: "What's the best mushroom substitute if I can't find wild mushrooms?",
    upvotes: 12,
    isAnswered: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: "user-top-1", username: "risotto_king", score: 9840, xpTotal: 12400, currentStreak: 21, isCurrentUser: false },
  { rank: 2, userId: "user-top-2", username: "chef_sophie_fan", score: 8920, xpTotal: 10200, currentStreak: 15, isCurrentUser: false },
  { rank: 3, userId: "user-top-3", username: "midnight_cook", score: 8650, xpTotal: 9800, currentStreak: 12, isCurrentUser: false },
  { rank: 4, userId: "user-top-4", username: "pasta_queen", score: 7400, xpTotal: 8900, currentStreak: 8, isCurrentUser: false },
  { rank: 5, userId: "user-top-5", username: "foodie_sara", score: 6800, xpTotal: 7200, currentStreak: 5, isCurrentUser: false },
  { rank: 6, userId: "user-top-6", username: "weekend_warrior", score: 5900, xpTotal: 6100, currentStreak: 3, isCurrentUser: false },
  { rank: 7, userId: "me-user", username: "you", score: 4200, xpTotal: 4800, currentStreak: 5, isCurrentUser: true },
  { rank: 8, userId: "user-top-8", username: "kitchen_newbie", score: 3800, xpTotal: 4200, currentStreak: 2, isCurrentUser: false },
];

export const MOCK_MYSTERY_BOX_SUBMISSIONS: MysteryBoxSubmission[] = [
  {
    id: "mb-1",
    userId: "user-2",
    username: "foodie_sara",
    mysteryIngredient: "Pomegranate",
    dishIdea: "Moroccan lamb tagine with pomegranate molasses glaze and preserved lemon couscous",
    isFeaturedOnTv: true,
    submittedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "mb-2",
    userId: "user-3",
    username: "chef_at_home",
    mysteryIngredient: "Pomegranate",
    dishIdea: "Duck breast with pomegranate and walnut sauce, served on a bed of jeweled saffron rice",
    isFeaturedOnTv: false,
    submittedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "mb-3",
    userId: "user-9",
    username: "spice_master",
    mysteryIngredient: "Pomegranate",
    dishIdea: "Grilled salmon with pomegranate salsa, sumac yogurt and micro herb salad",
    isFeaturedOnTv: false,
    submittedAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
];
